### ISSUE TITLE
Changing base table columns causes rendering loop

### ISSUE THREAD

**Issue by SchrodingersGat** [icflorescu/mantine-datatable#759]
**Describe the bug**

I have been trying to track down a bug I have experienced in the [InvenTree project](https://github.com/inventree/InvenTree/)

When using the `useDataTableColumns`  hook, if the `columns` parameter changes, the order of rendered columns does not *always* match the provided order of columns.

**To Reproduce**

1. Create a simple table with the `useDataTableColumns` hook, e.g. 

```typescript

 const myColumns = useMemo(() => {
    return [
        ...
    ];
 }, []);

  const tableColumns = useDataTableColumns({
    key: 'my-table',
    columns: dataColumns,
  });
```

2. Render the table, which stores the column order data to local storage
3. Insert a new column (into `myColumns`) which is *not* at the end
4. The table will be rendered with the new column at the end.
5. Additionally, there may be multiple (ongoing, repeated) re-render hooks due to the mismatch of input and displayed column ordering

Additional calls to `setColumnOrder` do not seem to fix the problem, as the column order is "locked in" on first rendering call.

**Expected behavior**

The displayed column order always matches the order of the supplied columns.

**Additional context**

I believe that the bug arises from this line:

https://github.com/icflorescu/mantine-datatable/blob/3ee01b0a3cb0de9b04fc2e20f00e3fded5084423/package/hooks/useDataTableColumns.ts#L123

In fact, I have resolved the issue entirely by commenting out this line.

So, this indicates that the `alignedColumnsOrder` is not being cached or updated correctly:

From:

https://github.com/icflorescu/mantine-datatable/blob/3ee01b0a3cb0de9b04fc2e20f00e3fded5084423/package/hooks/useDataTableColumns.ts#L41

```typescript
  function alignColumnsOrder<T>(columnsOrder: string[], columns: DataTableColumn<T>[]) {
    const updatedColumnsOrder: string[] = [];
    columnsOrder.forEach((col) => {
      if (columns.find((c) => c.accessor === col)) {
        updatedColumnsOrder.push(col);
      }
    });
    columns.forEach((col) => {
      if (!updatedColumnsOrder.includes(col.accessor as string)) {
        updatedColumnsOrder.push(col.accessor as string);
      }
    });
    return updatedColumnsOrder;
  }
```

This function orders the columns by first looking in the stored columns, and then appending any newly detected columns *after* that.

However, there is a logic or sequence error which means that the old columns order is always written back to the localStorage.

**Comment by SchrodingersGat** [comment]
I'm not sure the best way to handle this, it seems like a potential race condition? Perhaps an option to disable the call to `setColumnsOrder(alignedColumnsOrder)`?

**Comment by SchrodingersGat** [comment]
Hi @icflorescu sorry to pester you again, I have not been able to work out an external solution for this. Any chance you have some insight?

**Comment by SchrodingersGat** [comment]
Here is a screenshot of the issue in play, the `...` column should be fixed to the right of the table

<img width="1619" height="391" alt="Image" src="https://github.com/user-attachments/assets/f490747d-8eeb-4f0c-add5-0ecd681f80b5" />


The final "actions" column is always appended in the end:

```typescript
  // Update column visibility when hiddenColumns change
  const dataColumns: any = useMemo(() => {
    let cols: TableColumn[] = columns.filter((col) => col?.hidden != true);

    cols = cols.map((col) => {
      // If the column is *not* switchable, it is always visible
      // Otherwise, check if it is "default hidden"

      const hidden: boolean =
        col.switchable == false
          ? false
          : (tableState.hiddenColumns?.includes(col.accessor) ?? false);

      // Wrap the render function with CopyableCell if copyable is enabled
      const originalRender = col.render;
      let wrappedRender = originalRender;

      if (col.copyable) {
        wrappedRender = (record: any, index?: number) => {
          const content =
            originalRender?.(record, index) ??
            resolveItem(record, col.accessor);

          // Determine the value to copy, ensuring it is always a string
          let rawCopyValue: unknown;
          if (typeof col.copyable === 'function') {
            rawCopyValue = col.copyable(record);
          } else {
            const accessor = col.copyAccessor ?? col.accessor;
            rawCopyValue = resolveItem(record, accessor);
          }
          const copyValue = rawCopyValue == null ? '' : String(rawCopyValue);

          if (window.isSecureContext && !!copyValue) {
            return <CopyableCell value={copyValue}>{content}</CopyableCell>;
          } else {
            return content;
          }
        };
      }

      return {
        ...col,
        hidden: hidden,
        resizable: col.resizable ?? true,
        title: col.title ?? fieldNames[col.accessor] ?? `${col.accessor}`,
        render: wrappedRender,
        cellsStyle: (record: any, index: number) => {
          const width = (col as any).minWidth ?? 100;
          return {
            minWidth: width
          };
        },
        titleStyle: (record: any, index: number) => {
          const width = (col as any).minWidth ?? 100;
          return {
            minWidth: width
          };
        }
      };
    });

    // If row actions are available, add a column for them
    if (tableProps.rowActions) {
      cols.push({
        accessor: ACTIONS_COLUMN_ACCESSOR,
        title: '   ',
        hidden: false,
        resizable: false,
        switchable: false,
        width: 50,
        render: (record: any, index?: number | undefined) => (
          <RowActions
            actions={tableProps.rowActions?.(record) ?? []}
            disabled={tableState.selectedRecords.length > 0}
            index={index}
          />
        )
      });
    }

    return cols;
  }, [
    columns,
    fieldNames,
    tableProps.rowActions,
    tableState.hiddenColumns,
    tableState.selectedRecords
  ]);
```

And then, I am using the `useDataTableColumns` hook:

```typescript
  // Final state of the table columns
  const tableColumns = useDataTableColumns({
    key: `${cacheKey}-${columnHash}`,
    columns: dataColumns,
    getInitialValueInEffect: true
  });
```

I thought I had managed to work around this, however it has popped up again. Would appreciate any comment, or insight into what other data I might be able to provide to narrow in on this issue.

**Comment by ful-stackz** [comment]
I'm experiencing the same issue. Tried the same as @SchrodingersGat, but it doesn't work. See TL;DR below.

What worked for me was having a `useEffect` that resets the columns order and width when the component is mounted. **Note** that this doesn't work with hot-reload, ie. the following scenario yields a negative result:
1. Add a new column to the `useDataTableColumns` hook
2. Save the file in your IDE
3. Hot-reload is triggered
4. The new column appears at the end (blah not nice)

However, it does work as intended when you refresh the page. Which is what would happen on release anyway, ergo this is good enough in my case. Note that the hidden/toggled columns are persisted correctly, no issues there.

This will **NOT** work for you if:
- your columns are resizable by the user
- your columns are orderable by the user
- \** It will work, but the resize and reorder changes will not be persisted between page refreshes

---

**TL;DR**

**🩹 Workaround:** reset the columns **order** and **width** when the component is mounted.

**📝 Snippet:**

```jsx
const tableColumns = useDataTableColumns({
  key: '<key-here>',
  columns: [/* columns here */],
});

useEffect(() => {
  tableColumns.resetColumnsOrder();
  tableColumns.resetColumnsWidth();
}, []);
```

**Comment by icflorescu** [comment]
This should be fixed in v9.2.

**Comment by SchrodingersGat** [comment]
@icflorescu is there any available information on what's changed with v9? There's currently [nothing in the changelog](https://github.com/icflorescu/mantine-datatable/blob/main/CHANGELOG.md)

**Comment by icflorescu** [comment]
@SchrodingersGat Thanks for noticing, updated now.

**Comment by SchrodingersGat** [comment]
Unfortunately I can still reproduce this in v9

<img width="1841" height="650" alt="Image" src="https://github.com/user-attachments/assets/22eeaad2-1327-45e1-9a5e-f342015e2c40" />

Here the "..." column is confirmed to be the last one in "memory" - but this is not being reflected in the table.

The key difference between this any other tables is that the table has columns added *after* initial render.

I have this code currently:

```typescript
  const tableColumnHash = useMemo(() => {
    const columnNames = dataColumns.map((col: any) => col.accessor).join(', ');
    console.log("Columns:", columnNames);
    return hashString(columnNames);
  }, [dataColumns]);

  // Final state of the table columns
  const tableColumns = useDataTableColumns({
    key: `${cacheKey}-${tableColumnHash}`,
    columns: dataColumns,
    getInitialValueInEffect: false
  });
```

which is logging the following messages, showing the additional column `parameter_235` (which is `Length [mm]` in this case):

<img width="594" height="216" alt="Image" src="https://github.com/user-attachments/assets/a7208a11-ed8b-4ee9-af31-978741f5d29f" />

**Comment by SchrodingersGat** [comment]
I *think* that I have it working with the following approach:

```typescript
  const tableColumnHash = useMemo(() => {
    const columnNames = dataColumns.map((col: any) => col.accessor).join(', ');
    return hashString(columnNames);
  }, [dataColumns]);

  // Final state of the table columns
  const tableColumns = useDataTableColumns({
    key: cacheKey,
    columns: dataColumns,
    getInitialValueInEffect: false
  });

  // Reset column ordering and custom widths when the component is mounted
  // Ref: https://github.com/icflorescu/mantine-datatable/issues/759
  useEffect(() => {
    tableColumns.setColumnsOrder(dataColumns.map((col: any) => col.accessor));
  }, [tableColumnHash]);
```

The key here is to force-update a new column ordering (via `tableColumns.setColumnsOrder`) whenever the master set of columns changes 

So while this workaround "fixes" the immediate problem, I think it may point to a potential shortcoming of the library where updating the set of columns after rendering can force the new columns to the end of the list...

**Comment by icflorescu** [comment]
Perhaps @gfazioli can take a look at it when he has a spare moment
